---
kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-sd
  annotations:
    "getambassador.io/consul-resolver": "true"
data:
  consulAddress: "consul-server:8500"
  datacenter: "dc1"
  service: "qotm-proxy"
