global:
  enabled: true
  domain: consul
  image: "consul:1.4.2"
  datacenter: dc1

server:
  enabled: true
  replicas: 2
  bootstrapExpect: 2
  # enterpriseLicense:
  #   secretName: "consul-license"
  #   secretKey: "key"
  storage: 20Gi
  connect: true

client:
  enabled: true
  grpc: true

dns:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: NodePort

connectInject:
  enabled: true
  default: false 
